name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin master
      - run: npm install
      - run: npm nx affected --target=test --base=origin/master
      - run: npm nx affected --target=lint --base=origin/master
      - run: npm nx affected --target=build --base=origin/master
